resources:
  App\Entity\Greeting: ~
  App\Entity\Book:
    attributes:
      filters: ['book.name', 'book.date']
      normalization_context:
        groups: ['book_read']
    itemOperations:
      get:
        method: "GET"
        normalization_context:
          groups: ['book_all']
    properties:
      author:
        subresource:
          resourceClass: 'App\Entity\Author'
          collection: false
  App\Entity\Review: ~
  App\Entity\Author:
    attributes:
      order:
        lastname: ASC
      filters: ['author.name']
    properties:
      books:
        subresource:
          resourceClass: 'App\Entity\Book'
          collection: true
          maxDepth: 1