resources:
  App\Entity\Greeting: ~
  App\Entity\Book: ~
  App\Entity\Review: ~
  App\Entity\Author:
    properties:
      books:
        subresource:
          resourceClass: 'App\Entity\Book'
          collection: true